version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4000:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # Bookmark hold - Dont override node_modules inside the container
      - ./server:/app # Copy all files in server folder into /app inside the container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 # Default port
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password # Default password
      - PGPORT=5432 # Default port
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules # Bookmark hold - Dont override node_modules inside the container
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules # Bookmark hold - Dont override node_modules inside the container
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379